name: "Should Run Check"
author: huwqchn
description: "Determine whether CI should run based on commit message"
inputs:
  prefixes:
    description: "Prefixes to skip (e.g., chore docs)"
    required: false
    default: "chore docs"
outputs:
  run-check:
    description: "Whether the check should run"
    value: ${{ steps.set-output.outputs.run-check }}
runs:
  using: "composite"
  steps:
    - name: Get latest commit message
      id: get-commit
      shell: bash
      run: echo "message=$(git log -1 --pretty=%B)" >> $GITHUB_OUTPUT

    - name: Parse commit message args
      id: parse
      uses: ./.github/actions/parse-commit-args

    - name: Decide whether to run check
      id: set-output
      shell: bash
      run: |
        message="${{ steps.get-commit.outputs.message }}"
        echo "Commit message: $message"

        # Default to true (run the check)
        run_check="true"

        for prefix in ${{ inputs.prefixes }}; do
          if [[ "$message" =~ ^$prefix ]]; then
            echo "Matched prefix: $prefix"
            run_check="false"
            break
          fi
        done

        skip_check="${{ steps.parse.outputs.skip-check }}"
        if [ "$skip_check" = "true" ]; then
          echo "Parsed flag --skip-check is set, so skipping check"
          run_check="false"
        fi

        echo "run-check=$run_check" >> "$GITHUB_OUTPUT"
