#!/bin/bash

if pgrep easyeffects; then
	pkill easyeffects
	echo "Off" >$HOME/.config/eww/player/status/eq-status
	exit 1
else
	exec easyeffects --gapplication-service &
	echo "On" >$HOME/.config/eww/player/status/eq-status
fi
exit
