alias c='clear'
# alias ls="colorls"
alias s='neofetch'
alias lg='lazygit'
alias lnpm ='lazynpm'
alias ra='ranger'
alias t='tmux'
alias ta='tmux a'
alias cdiff='colordiff'
alias e='emacs -nw'
alias ep='export https_proxy="127.0.0.1:19180" && export http_proxy="127.0.0.1:19180"'
alias doom='~/.emacs.d/bin/doom'
