source ~/.config/zsh/env.zsh
source ~/.config/zsh/aliases.zsh
source ~/.config/zsh/plugins.zsh
source ~/.config/zsh/vi.zsh
source ~/.config/zsh/fzf.zsh
source ~/.config/zsh/mappings.zsh

# autopair-init
# source ~/.zim/modules/fzf-tab/fzf-tab.plugin.zsh

source ~/.config/zsh/prompt.zsh
