source ~/.config/zsh/theme.zsh
source ~/.config/zsh/env.zsh
source ~/.config/zsh/aliases.zsh
source ~/.config/zsh/plugins.zsh
source ~/.config/zsh/vi.zsh
source ~/.config/zsh/fzf.zsh
source ~/.config/zsh/mappings.zsh

autopair-init
# beeping is annoying
unsetopt BEEP
# source ~/.zim/modules/fzf-tab/fzf-tab.plugin.zsh

source ~/.config/zsh/prompt.zsh
source ~/.config/zsh/eval.zsh
