keys:
  - &johnson E23E274D412D4C761A871B1E776C7FC245E58F55
  - &eir age13srgr0k8nkwfh6yuptk9g3ly9aslsatmav4cvje04z58lp8d3d6q0d9g6j

creation_rules:
  - path_regex: ^(\./)?secrets/([^/]+\.(ya?ml|json|ini|env)|[^/]+)$
    key_groups:
      - age:
          - *eir
        pgp:
          - *johnson
