[files]
extend-exclude = ["themes/*", "*.age", "*.pub", "*.glsl", "*.lua"]
ignore-dot = true
ignore-files = true

[type.age]
extend-glob = ["*.age", "*.pub"]
check-file = false

[default]
binary = false

[default.extend-words]
ags = "ags"
crypted = "crypted"
nore = "nore"
noice = "noice"
