[files]
extend-exclude = [
  "themes/*",
  "*.age",
  "*.pub",
  "*.glsl",
  "config/nvim/lua/plugins/extras/editor/neo-tree.lua",
]
ignore-dot = true
ignore-files = true

[type.age]
extend-glob = ["*.age", "*.pub"]
check-file = false

[default]
binary = false

[default.extend-words]
ags = "ags"
crypted = "crypted"
nore = "nore"
noice = "noice"
ot = "ot"
Ot = "Ot"
ba = "ba"
