{
  config,
  lib,
  self,
  ...
}: let
  inherit (lib) mkIf;
  cfg = config.my.security;
  inherit (config.my) name;
in {
  config = mkIf cfg.enable {
    home.file.".ssh/id_${name}.pub".source = "${self}/secrets/${name}/ssh.pub";

    programs.ssh = {
      enable = true;

      # All my ssh private key are generated by `ssh-keygen -t ed25519 -a 256 -C "xxx@xxx"`
      # Config format:
      #   Host —  given the pattern used to match against the host name given on the command line.
      #   HostName — specify nickname or abbreviation for host
      #   IdentityFile — the location of your SSH key authentication file for the account.
      # Format in details:
      #   https://www.ssh.com/academy/ssh/config
      extraConfig = ''
        # a private key that is used during authentication will be added to ssh-agent if it is running
        AddKeysToAgent yes

        Host 192.168.*
          # allow to securely use local SSH agent to authenticate on the remote machine.
          # It has the same effect as adding cli option `ssh -A user@host`
          ForwardAgent yes
          # holds my homelab~
          IdentityFile ~/.ssh/id_ed25519.pub
          # Specifies that ssh should only use the identity file explicitly configured above
          # required to prevent sending default identity files first.
          IdentitiesOnly yes

        Host ymir
          HostName 192.168.5.11
          Port 22
      '';
    };
    home.persistence = {
      "/persist/${config.home.homeDirectory}".directories = [".ssh"];
    };
  };
}
