source ~/.config/zsh/theme.zsh
source ~/.config/zsh/env.zsh
source ~/.config/zsh/aliases.zsh
source ~/.config/zsh/plugins.zsh
source ~/.config/zsh/vi.zsh
source ~/.config/zsh/fzf.zsh
source ~/.config/zsh/mappings.zsh

autopair-init
# beeping is annoying
unsetopt BEEP
# source ~/.zim/modules/fzf-tab/fzf-tab.plugin.zsh

source ~/.config/zsh/prompt.zsh
source ~/.config/zsh/eval.zsh

# Check if neofetch is installed
if command -v neofetch &> /dev/null; then
    # Check if the configuration file exists
    if [ -f $HOME/.config/neofetch/config_small.conf ]; then
        neofetch --config $HOME/.config/neofetch/config_tokyonight.conf
    else
        neofetch
    fi
else
    echo "neofetch is not installed."
fi
