#! /bin/sh

export BSPWM_CONFIG="${XDG_CONFIG_HOME:-$HOME/.config}/bspwm"

LOGS=~/.cache/bspwm/logs

# if LOGS not exist, create it
if [ ! -d "$LOGS" ]; then
	mkdir -p $LOGS
fi

exec >$LOGS/bspwm.log 2>&1

# Get colors from .Xresources #
xrdb ~/.Xresources
getcolors() {
	FOREGROUND=$(xrdb -query | grep 'foreground:' | awk '{print $NF}')
	BACKGROUND=$(xrdb -query | grep 'background:' | awk '{print $NF}')
	BLACK=$(xrdb -query | grep 'color0:' | awk '{print $NF}')
	RED=$(xrdb -query | grep 'color1:' | awk '{print $NF}')
	YELLOW=$(xrdb -query | grep 'color2:' | awk '{print $NF}')
	GREEN=$(xrdb -query | grep 'color3:' | awk '{print $NF}')
	BLUE=$(xrdb -query | grep 'color4:' | awk '{print $NF}')
	MAGENTA=$(xrdb -query | grep 'color5:' | awk '{print $NF}')
	CYAN=$(xrdb -query | grep 'color6:' | awk '{print $NF}')
	WHITE=$(xrdb -query | grep 'color7:' | awk '{print $NF}')
	BRIGHT_BLACK=$(xrdb -query | grep 'color8:' | awk '{print $NF}')
	BRIGHT_RED=$(xrdb -query | grep 'color9:' | awk '{print $NF}')
	BRIGHT_YELLLOW=$(xrdb -query | grep 'color10:' | awk '{print $NF}')
	BRIGHT_BLUE=$(xrdb -query | grep 'color11:' | awk '{print $NF}')
	BRIGHT_BLUE=$(xrdb -query | grep 'color12:' | awk '{print $NF}')
	BRIGHT_MAGENTA=$(xrdb -query | grep 'color13:' | awk '{print $NF}')
	BRIGHT_CYAN=$(xrdb -query | grep 'color14:' | awk '{print $NF}')
	BRIGHT_WHITE=$(xrdb -query | grep 'color15:' | awk '{print $NF}')
}
getcolors

# Mulithead behavior
bspc monitor -d I II III IV V VI VII VIII IX X
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

bspc config border_width 4
bspc config window_gap 12

bspc config split_ratio 0.50
bspc config single_monocle true
bspc config borderless_monocle true
bspc config gapless_monocle true

# padding
bspc config top_padding 8
bspc config bottom_padding 8
bspc config left_padding 8
bspc config right_padding 8

# border color
bspc config focused_border_color "$FOREGROUND"
bspc config normal_border_color "$BACKGROUND"
bspc config active_border_color "$MAGENTA"
bspc config presel_feedback_color "$GREEN"

# mouse
bspc config pointer_modifier super
# bspc config pointer_action1 move
# bspc config pointer_action3 resize_side
# bspc config pointer_action3 resize_corner

# manage rules
bspc rule -a Gimp state=floating follow=on
bspc rule -a 1Password state = floating
bspc rule -a Spotify state = floating desktop='^5' follow=on
# bspc rule -a Chromium desktop='^2'
bspc rule -a Peek state=floating
bspc rule -a Screenkey manage=off
bspc rule -a Zathura state=tiled
bspc rule -a Emacs state=tiled
bspc rule -a GLava state=floating layer=below sticky=true locked=true border=off focus=off center=true follow=off rectangle=3840x2160+0+0

"$BSPWM_CONFIG/autostart" &
