#! /bin/sh

pgrep -x sxhkd >/dev/null || sxhkd &

LOGS=~/.cache/bspwm/logs

exec >$LOGS/bspwm.log 2>&1
# $HOME/.scripts/setcursor.sh

# Get colors from .Xresources #
xrdb ~/.Xresources
# xmodmap ~/.Xmodmap
getcolors() {
	FOREGROUND=$(xrdb -query | grep 'foreground:' | awk '{print $NF}')
	BACKGROUND=$(xrdb -query | grep 'background:' | awk '{print $NF}')
	BLACK=$(xrdb -query | grep 'color0:' | awk '{print $NF}')
	RED=$(xrdb -query | grep 'color1:' | awk '{print $NF}')
	YELLOW=$(xrdb -query | grep 'color2:' | awk '{print $NF}')
	GREEN=$(xrdb -query | grep 'color3:' | awk '{print $NF}')
	BLUE=$(xrdb -query | grep 'color4:' | awk '{print $NF}')
	MAGENTA=$(xrdb -query | grep 'color5:' | awk '{print $NF}')
	CYAN=$(xrdb -query | grep 'color6:' | awk '{print $NF}')
	WHITE=$(xrdb -query | grep 'color7:' | awk '{print $NF}')
	BRIGHT_BLACK=$(xrdb -query | grep 'color8:' | awk '{print $NF}')
	BRIGHT_RED=$(xrdb -query | grep 'color9:' | awk '{print $NF}')
	BRIGHT_YELLLOW=$(xrdb -query | grep 'color10:' | awk '{print $NF}')
	BRIGHT_BLUE=$(xrdb -query | grep 'color11:' | awk '{print $NF}')
	BRIGHT_BLUE=$(xrdb -query | grep 'color12:' | awk '{print $NF}')
	BRIGHT_MAGENTA=$(xrdb -query | grep 'color13:' | awk '{print $NF}')
	BRIGHT_CYAN=$(xrdb -query | grep 'color14:' | awk '{print $NF}')
	BRIGHT_WHITE=$(xrdb -query | grep 'color15:' | awk '{print $NF}')
}
getcolors

# Mulithead behavior
bspc monitor -d I II III IV V VI VII VIII IX X
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

bspc config border_width 4
bspc config window_gap 12

bspc config split_ratio 0.50
bspc config single_monocle true
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc config top_padding 8
bspc config bottom_padding 8
bspc config left_padding 8
bspc config right_padding 8
bspc config focused_border_color "$FOREGROUND"
bspc config normal_border_color "$BACKGROUND"
bspc config active_border_color "$MAGENTA"
bspc config presel_feedback_color "$GREEN"

bspc config pointer_modifier super
# bspc config pointer_action1 move
# bspc config pointer_action3 resize_side
# bspc config pointer_action3 resize_corner


bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Peek state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Zathura state=tiled
bspc rule -a Emacs state=tiled
bspc rule -a GLava state=floating layer=below sticky=true locked=true border=off focus=off center=true follow=off rectangle=1920x1080+0+0


sleep 10 && $HOME/.config/bspwm/scripts/bspfloat floating 5 &> $HOME/.log.bspfloat.txt &
$HOME/.scripts/inverse-scroll.sh
$HOME/.config/polybar/launch.sh
$HOME/.config/conky/Auva/start.sh &
eww daemon &
xsetroot -cursor_name left_ptr &
/usr/lib/mate-polkit/polkit-mate-authentication-agent-1 &
xfce4-power-manager &
ukui-window-switch &
dunst &
fcitx5 &
picom &
udiskie &
parcellite &
greenclip daemon &
gebaard -b
/usr/bin/emacs --daemon &
alttab -d 1 -i 108x108 -bg "#1a1b26" -fg "#a9b1d6" -t 224x256 -frame "#9ece6a" -bc "#7aa2f7" -bw 5 -inact "#4abaaf" &
feh --bg-fill -no-fehbg ~/OneDrive/Wallpapers/tokyo-night31.png
# update eww screen height and width

# Retrieve the screen resolution information
# RESOLUTION=$(xrandr | awk '/\*/ {print $1}')
# WIDTH=$(echo $RESOLUTION | cut -d 'x' -f1)
# HEIGHT=$(echo $RESOLUTION | cut -d 'x' -f2)
# eww update screen_width = WIDTH
# eww update screen_height = HEIGHT

# bash $HOME/.config/bspwm/scripts/fix-plank
# plank &
