#!/bin/sh

pgrep -x sxhkd >/dev/null || sxhkd &
picom &
xsetroot -cursor_name left_ptr &
feh --bg-fill -no-fehbg ~/OneDrive/Wallpapers/tokyo-night31.png &
sleep 10 && $HOME/.config/bspwm/scripts/bspfloat floating 5 &> $HOME/.log.bspfloat.txt &

# Authentication agent
/usr/lib/mate-polkit/polkit-mate-authentication-agent-1 &

$HOME/.scripts/inverse-scroll.sh &
$HOME/.config/polybar/launch.sh &
$HOME/.config/conky/Auva/start.sh &
eww daemon &
xfce4-power-manager &
ukui-window-switch &

killall dunst
dunst > /dev/null 2> /dev/null &

fcitx5 &
udiskie &
parcellite &
greenclip daemon &

killall blueman-applet
killall pa-applet
killall nm-applet
blueman-applet &
pa-applet --disable-key-grabbing --disable-notifications & 
nm-applet &

thunar --daemon &

# gebaard -b

# /usr/bin/emacs --daemon &
# alttab -d 1 -i 108x108 -bg "#1a1b26" -fg "#a9b1d6" -t 224x256 -frame "#9ece6a" -bc "#7aa2f7" -bw 5 -inact "#4abaaf" &

# bash $HOME/.config/bspwm/scripts/fix-plank
# plank &
