#!/bin/bash

# Function to check for the presence of a battery
have_battery() {
	if ls /sys/class/power_supply/BAT* 1>/dev/null 2>&1; then
		return 0
	else
		exit 1
	fi
}

battery=/sys/class/power_supply/BAT0/

percentage() {
	cat "$battery/capacity"
}

status() {
	cat "$battery/status"
}

charging_animation() {
	local icons=("󰢟" "󰢜" "󰂆" "󰂇" "󰂈" "󰢝" "󰂉" "󰢞" "󰂊" "󰂋" "󰂅")
	while [[ "$(status)" != "Full" ]]; do
		for icon in "${icons[@]}"; do
			# eww update battery-icon="$icon"
			echo "$icon"
			sleep 0.3
		done
	done
}

low_power_alert_animation() {
	local icons=("󱃍" "󰂎")
	while [[ "$(status)" == "Discharging" ]]; do
		for icon in "${icons[@]}"; do
			# eww update battery-icon="$icon"
			echo "$icon"
			sleep 0.3
		done
	done
}

level() {
	local capacity=$(percentage)
	if [[ $capacity -ge 80 ]]; then
		echo "high"
	elif [[ $capactiy -ge 20 ]]; then
		echo "mid"
	else
		echo "low"
	fi
}

icon() {
	while true; do
		local icon
		if [[ "$(status)" == "Charging" ]]; then
			charging_animation
			continue
		elif [[ "$(status)" == "Full" ]]; then
			icon="󰂅"
			eww update battery-icon="󰂅"
			echo "$icon"
			sleep 1
			continue
		fi

		local capacity=$(percentage)
		if [[ $capacity -eq 100 ]]; then
			icon="󰁹"
		elif [[ $capacity -gt 90 ]]; then
			icon="󰂂"
		elif [ $capacity -gt 80 ]; then
			icon="󰂁"
		elif [ $capacity -gt 70 ]; then
			icon="󰂀"
		elif [ $capacity -gt 60 ]; then
			icon="󰁿"
		elif [ $capacity -gt 50 ]; then
			icon="󰁾"
		elif [ $capacity -gt 40 ]; then
			icon="󰁽"
		elif [ $capacity -gt 30 ]; then
			icon="󰁼"
		elif [ $capacity -gt 20 ]; then
			icon="󰁻"
		elif [ $capacity -gt 10 ]; then
			notify-send -u critical "Battery Low" "Connect Charger"
			icon="󰁺"
		else
			notify-send -u critical "Battery Low" "Connect Charger"
			low_power_alert_animation
		fi
		eww update battery-icon="$icon"
		echo "$icon"
		sleep 1
	done
}

# Check if we have a battery
if have_battery; then
	# Process command line arguments
	case "$1" in
	--percentage)
		percentage
		exit 0
		;;
	--status)
		status
		exit 0
		;;
	--exists)
		echo "true"
		exit 0
		;;
	--icon)
		icon
		exit 0
		;;
	--level)
		level
		exit 0
		;;
	*)
		echo "Usage: $0 --percentage | --status | --exists | --icon | --level"
		exit 1
		;;
	esac
else
	echo "false"
	exit 1
fi
