#!/bin/bash

# Function to check for the presence of a battery
have_battery() {
	if ls /sys/class/power_supply/BAT* 1>/dev/null 2>&1; then
		return 0
	else
		exit 1
	fi
}

battery=/sys/class/power_supply/BAT0/

percentage() {
	cat "$battery/capacity"
}

status() {
	cat "$battery/status"
}

charging_animation() {
	local icons=("󰢟 " "󰢜 " "󰂆 " "󰂇 " "󰂈 " "󰢝 " "󰂉 " "󰢞 " "󰂊 " "󰂋 " "󰂅 ")
	while [[ "$(status)" == "Charging" ]]; do
		for icon in "${icons[@]}"; do
			eww update battery-icon="$icon"
			eww update battery-percent="$(percentage)"
			sleep 0.5
		done
	done
}

low_power_alert_animation() {
	local icons=("󱃍 " "󰂎 ")
	while [[ "$(status)" == "Discharging" ]]; do
		for icon in "${icons[@]}"; do
			eww update battery-icon="$icon"
			eww update battery-percent="$(percentage)"
			sleep 0.5
		done
	done
}

state() {
	local capacity=$(percentage)
	if [[ $capacity -ge 80 ]]; then
		echo "High"
	elif [[ $capactiy -ge 20 ]]; then
		echo "Midium"
	else
		echo "Low"
	fi
}

update() {
	while true; do
		local icon
		eww update battery-state="$(state)"
		eww update battery-percent="$(percentage)"
		if [[ "$(status)" == "Charging" ]]; then
			eww update battery-state="Charging"
			charging_animation
			continue
		elif [[ "$(status)" == "Full" ]]; then
			eww update battery-state="Full"
			eww update battery-icon="󰂅 "
			sleep 1
			continue
		fi

		local capacity=$(percentage)
		if [[ $capacity -eq 100 ]]; then
			icon="󰁹 "
		elif [[ $capacity -gt 90 ]]; then
			icon="󰂂 "
		elif [ $capacity -gt 80 ]; then
			icon="󰂁 "
		elif [ $capacity -gt 70 ]; then
			icon="󰂀 "
		elif [ $capacity -gt 60 ]; then
			icon="󰁿 "
		elif [ $capacity -gt 50 ]; then
			icon="󰁾 "
		elif [ $capacity -gt 40 ]; then
			icon="󰁽 "
		elif [ $capacity -gt 30 ]; then
			icon="󰁼 "
		elif [ $capacity -gt 20 ]; then
			icon="󰁻 "
		elif [ $capacity -gt 10 ]; then
			notify-send -u critical "Battery Low" "Connect Charger"
			icon="󰁺 "
		else
			notify-send -u critical "Battery Low" "Connect Charger"
			low_power_alert_animation
		fi
		eww update battery-icon="$icon"
		echo "$icon"
		sleep 1
	done
}

# Check if we have a battery
if have_battery; then
	# Process command line arguments
	case "$1" in
	--percentage)
		percentage
		exit 0
		;;
	--status)
		status
		exit 0
		;;
	--exists)
		echo "true"
		exit 0
		;;
	--update)
		eww update battery-active=true
		update
		exit 0
		;;
	--state)
		state
		exit 0
		;;
	*)
		echo "Usage: $0 --percentage | --status | --exists | --update | --state"
		exit 1
		;;
	esac
else
	echo "false"
	exit 1
fi
