return {
  "saturn.plugins.core.lsp",
  "saturn.plugins.core.cmp",
  "saturn.plugins.core.illuminate",
  "saturn.plugins.core.mason",
  "saturn.plugins.core.treesitter",
  "saturn.plugins.core.alpha",
  "saturn.plugins.core.colorscheme",
  "saturn.plugins.core.impatient",
  "saturn.plugins.core.nvim-tree",
  "saturn.plugins.core.comment",
  "saturn.plugins.core.indentline",
  "saturn.plugins.core.project",
  "saturn.plugins.core.autopairs",
  "saturn.plugins.core.dap",
  "saturn.plugins.core.telescope",
  "saturn.plugins.core.bufferline",
  "saturn.plugins.core.gitsigns",
  "saturn.plugins.core.lualine",
  "saturn.plugins.core.toggleterm",
  "saturn.plugins.core.whichkey",
  "saturn.plugins.core.lir",
  "saturn.plugins.core.breadcrumbs",
}

