{
  userName = "johnson";
  userFullName = "Johnson Hu";
  userEmail = "johnson.wq.hu@gmail.com";
  userTheme = "tokyonight-storm";
  userWall = "tokyonight/cafe-at-night_00_3840x2160.png";
  # generated by `mkpasswd -m scrypt`
  # we have to use initialHashedPassword here when using tmpfs for /
  initialHashedPassword = "$y$j9T$UtvejDe22fK.4ok7ZyI1Y/$.vc/kQ3hRFbb2ntOCQQna3CcWWP6dxwtEAE1O9bWcO8";
  # TODO: Generate a public key that can login to all my devices and servers.
  # store the privaet key in Yukikey
}
