github_token: ENC[AES256_GCM,data:7mMA70Q3k4oU1T96pYpY2l2+6Kq3gpnsuWbpcMaKiHm+DJcBz7y4xA==,iv:OVkbKfFzW+rkaElKNO1eMA763CWW2tRT5zhXGoK8wEQ=,tag:WJt6EFDfpL6YXk4lth0ZOA==,type:str]
google_cloud_project: ENC[AES256_GCM,data:ILNHPS5KpeDjEblTAFwfZl5r0j7dXg==,iv:zlVmkmkAiP67u/Y1SiVlechJcKwlAglM3Myp31ufUcE=,tag:+YY5IjmYhxWjwOd1am2Dvw==,type:str]
atuin_key: ENC[AES256_GCM,data:D2OpwIAGX40gYytwjuR3HcpRiCwkdoUjRhUlsHtQeNX+c2RPyLaDffeNe/IdsK0BH1SE2XcLgmESQ72k5nfXzUE8uKg=,iv:OsfsjJjP72S0U5GKaXTYnNCfN6FJE7aA8JTGMRJXbkU=,tag:i043k3xI6s+9CzZzrfhXCA==,type:str]
atuin_name: ENC[AES256_GCM,data:Mqb19BMgNZlrrQ==,iv:RTqQBH7ejCFw/pQ/pakU/waBbENCZXNfiO9T3Wi3HA8=,tag:CTl5V1ZBXrLSFolAM3M5lg==,type:str]
atuin_password: ENC[AES256_GCM,data:EyURbwaWgVwVu5o=,iv:cSNKLv+zGFkEw0XsIcK7zo6pzIrEfi68XVZaXi9K7hE=,tag:0hxFNCiKP0so5tu2j4MYKg==,type:str]
atuin_keys: ENC[AES256_GCM,data:/k9dqWAk2+5Ug4ifXTMfHlP/md1yaB4CeBngzzlvoX8mFBdsygScLzYSmxn/bP2ddoCbyWa6XA/OgG/l42azGBJeqwb5pDq56yzVDrIFN2vi/iK5WVCQ3KMARLq1Q/MBr8KnzICsO3hoaiPEZfCCZksdXrqa1g+CcxoOws5tCK134S7MZyKykzyQ3adjGhg=,iv:5Tm1JSHWkf6ByhqDx+lgaeBxDj7EJtRhWzYU40vB0vE=,tag:JwA+sqjB8zmUGIVLBOdT/g==,type:str]
spotify_client_id: ENC[AES256_GCM,data:dtdY6XOwkKxQqx1RveNG0So+TA8qBVVBrsbHoTa7Uuo=,iv:HpK0rFvU69qZupq5d2q2gxW21cPzQKKklasTcpLiBKI=,tag:E9f9u42PNj8Y4f2a8ayOSA==,type:str]
u2f_keys: ENC[AES256_GCM,data:D8UfGXVwPepW6/F354kIkV+D+vmn1bqZOUGjB/CdiMoLMcpGPyPbQtJ9e5WPV2GJtXEN0f2sO7IoDHvw6ZhZMIks5N6WwsnYt69te5VrtoMtviB1PLsRFhnDzD2C2T4UhnxvJP1b/RkfzShg9oVGXt2YuCoaMmOxPQ1YX+/qz0kHzUOa7TXRKEFZByF2RmiKR2bNiR1H0OtQLhEGuspM7peTscwKyGacmF/2pbJTj9FYOAhL/UtZ39QYKRV1ZNwHwHKUAkWTd03p9ybxjbV+80qUUfEek3MgbbT/ZjxhD3PUvWGN+40MPf7bC95vKtYwP2VHyQtRM95v/SRQAwzC/dUvXz+VTcrE7VfJ9nMyuH+IVzK8MeTPieb+2oTRgOKIb7o6wSNMDegQRKjT5VJDnChFKlk4nNczwJVmiDT40eGMw45tLqm8HAoPrIFbQ4GXRqg+Bi59zIINuUFWcidI5ytEJRAyXUvLX7XCgyx2UQipJIQValyLh0RQH6gClWlSTmR2ogtUwmZNqwVegCuGV9b1UMr2sBflcjQIBXJZdoMiy9Bg+czWsUyqScXiZyMKSrXZG7wRjPHPGnzDMasxGnpa3cn2wnLM/hcYCXQRsP9vuuJPghtj8tV7Vo7/F8qWPzioUUutAU/vqlx4mEHTKAVmpwa+uhmv8aaXQBNNIxVJFeWml5f5aZYxZsmBnhTuwAYPiArWp/PGoMyt2/C2TG7nqB9aA7tnb+0sZrmFiw67eW5iU/9lOWy2I9kFKqMpnmnAazfntvpKlfAaBQ==,iv:tazR/b5p7Pmo2ygD449n/JdPBBysBILiYk0TEO3qJZw=,tag:6i6arUKVz/M0VvGWzzIdlg==,type:str]
sops:
  age:
    - recipient: age1dru9s2hakwc4zjzh64z35nkt7uemgq4xc0vz5v5m8s2juy0edugs5esp5j
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhOUdrSWRaRE8yRE5LbXI0
        VE5WcVBMQ3VrYUNRSmNQbEQ4YmVZN3ZxMnpjCjhYUlpVdjhOK0RMYVd4K1gwM2FB
        ZFZ6RmhBZlBMZXhJajNwSFRHb0l4UEUKLS0tIFl1b3Qxc0h1R202clBncmFONkd0
        S0g3K0VSR0FHY0Vac3lDOGc0SEtzZ2cK+qpiGBQTDVK4/qt08WpK70fA5dIxe0xU
        cpnwxcLtI1zo2trkpDtT9fxXu89OiLecCzfhIJLksYBHX5Av6L4MKA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-10-16T18:58:17Z"
  mac: ENC[AES256_GCM,data:USD+ow0Zmfnq+J+Hc2pOYsEIx8oRxpCpag60OoJC4WYGEf06V+FQEmQ3HK+O0GrQpft4uN1cNSVGJzAslaCyZZB9d6oDxVDi9B4RFXsJ2Q2KlOwr8NAFAnu2EL5Ra4WhA4klz+XGanmle+VHvPqSk2lC/TbOuPmfMb+2d4zPSnk=,iv:HsKbjahSXweqiQ+VwmoQDHZrzx8NloW9W52TxKwqGTs=,tag:HpNn5QVk3oA6Af7CUW+zAA==,type:str]
  pgp:
    - created_at: "2025-08-19T00:38:58Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hF4DK+ZqT54JVUESAQdAuj3wYUdWqBjoRkhq/6EQKld7iAQPOGFYF+LjRU+V3Wcw
        /qpnoC+aAl5Kt8fTYTS8D/FTgSJvg0T3sSMT1DjBkW/fz01Og54Jf5Ahy7h7hI6G
        0l4BLc9nwW/L3ABy/bDjjE50MypImXhUIq6nsn+pjpSmbCMbh/l+K0WWBpBZRbRs
        PFjJlnM6biCwh5wLEk84Pv0LppPZnFoe6umJkcmYRc6mOMAsTSLdoQdPmJZIPqT+
        =rqc5
        -----END PGP MESSAGE-----
      fp: E23E274D412D4C761A871B1E776C7FC245E58F55
  unencrypted_suffix: _unencrypted
  version: 3.10.2
