name: "Parse Commit Args"
author: huwqchn
description: "Parse commit message args and output flags for workflow control"

inputs: {}

outputs:
  deploy:
    description: "Whether the commit message contains --deploy"
    value: ${{ steps.parse.outputs.deploy }}
  build:
    description: "Whether the commit message contains --build"
    value: ${{ steps.parse.outputs.build }}
  skip-checks:
    description: "Whether the commit message contains --skip-checks"
    value: ${{ steps.parse.outputs.skip-checks }}

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Get commit message
      id: get-commit
      shell: bash
      run: |
        commit_message=$(git log -1 --pretty=format:'%s')
        echo "message=$commit_message" >> "$GITHUB_OUTPUT"

    - name: Parse commit flags
      id: parse
      shell: bash
      env:
        MESSAGE: "${{ steps.get-commit.outputs.message }}"
      run: |
        echo "Commit message: $MESSAGE"

        deploy="false"
        build="false"
        skip_checks="false"

        if [[ "$MESSAGE" =~ (--deploy)([[:space:]]|$) ]]; then
          echo "Found --deploy flag"
          deploy="true"
        fi

        if [[ "$MESSAGE" =~ (--build)([[:space:]]|$) ]]; then
          echo "Found --build flag"
          build="true"
        fi

        if [[ "$MESSAGE" =~ (--skip-checks)([[:space:]]|$) ]]; then
          echo "Found --skip-checks flag"
          skip_checks="true"
        fi

        echo "deploy=$deploy" >> "$GITHUB_OUTPUT"
        echo "build=$build" >> "$GITHUB_OUTPUT"
        echo "skip-checks=$skip_checks" >> "$GITHUB_OUTPUT"
