#!/usr/bin/env zsh

source $XDG_CONFIG_HOME/eww/init

# Find and store total number of workspaces in an array
_workspaces=($(bspc query -D --names))

# Create a structure function to store values in json format
wrap() {
	local onclick="\"onclick\":\"$1\""
	local text="\"text\":\"$2\""
	local class="\"class\":\"$3\""
	echo "{$onclick,$text,$class}"
}

_query() {
	bspc query -D -d $1 --names | grep -q "$workspace"
}

# Pack current values into the structure with json format
_pack() {
	buffer="["
	# for workspace in "${_workspaces[@]}"; do
  seq ${#_workspaces} | while read -r workspace; do
		if _query ".focused"; then
			buffer+="$(wrap "bspc desktop -f $workspace" "󰺕" "focused_workspace"),"
		elif _query ".occupied"; then
			buffer+="$(wrap "bspc desktop -f $workspace" "" "occupied_workspace"),"
		else
			buffer+="$(wrap "bspc desktop -f $workspace" "" "empty_workspace"),"
		fi
	done

	buffer="${buffer::-1}]" # strip the trailing comma and terminate
	echo "$buffer" | awk '{print}'
}

# Run once on startup and then follow changes
_pack
bspc subscribe desktop node_add node_remove node_transfer 2> /dev/null | while read -r _; do
	_pack
	_quit &
done
