#!/bin/bash

# A script to toggle between various desktop layouts for bspwm, intended to be used for my polybar module.

CURRENT=$(cat $HOME/.config/bspwm/scripts/current-layout)

# Switch layouts

# Tiled
if [[ $CURRENT == "Tiled" ]]; then
        bsp-layout set tiled
        echo "Tiled" > $HOME/.config/bspwm/scripts/current-layout
fi

# Monocle
if [[ $CURRENT == "Monocle" ]]; then
        bsp-layout set monocle
        echo "Monocle" > $HOME/.config/bspwm/scripts/current-layout
fi

# Grid
if [[ $CURRENT == "Grid" ]]; then
        bsp-layout set grid
        echo "Grid" > $HOME/.config/bspwm/scripts/current-layout
fi

# Wide
if [[ $CURRENT == "Wide" ]]; then
        bsp-layout set wide
        echo "Wide" > $HOME/.config/bspwm/scripts/current-layout
fi

# Even
if [[ $CURRENT == "Even" ]]; then
        bsp-layout set even
        echo "Even" > $HOME/.config/bspwm/scripts/current-layout
fi
