#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

$HOME/.dotfiles/.scripts/inverse-scroll.sh
$HOME/.config/polybar/launch.sh

# Get colors from .Xresources #
xrdb ~/.Xresources
# xmodmap ~/.Xmodmap
getcolors() {
	FOREGROUND=$(xrdb -query | grep 'foreground:'| awk '{print $NF}')
	BACKGROUND=$(xrdb -query | grep 'background:'| awk '{print $NF}')
	BLACK=$(xrdb -query | grep 'color0:'| awk '{print $NF}')
	RED=$(xrdb -query | grep 'color1:'| awk '{print $NF}')
	GREEN=$(xrdb -query | grep 'color2:'| awk '{print $NF}')
	YELLOW=$(xrdb -query | grep 'color3:'| awk '{print $NF}')
	BLUE=$(xrdb -query | grep 'color4:'| awk '{print $NF}')
	MAGENTA=$(xrdb -query | grep 'color5:'| awk '{print $NF}')
	CYAN=$(xrdb -query | grep 'color6:'| awk '{print $NF}')
	WHITE=$(xrdb -query | grep 'color7:'| awk '{print $NF}')
}
getcolors

# Mulithead behavior
bspc monitor -d I II III IV V VI VII VIII IX X
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

bspc config border_width         5
bspc config window_gap           12

bspc config split_ratio          0.50
bspc config single_monocle			 false
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config top_padding          8
bspc config bottom_padding       8
bspc config left_padding         8
bspc config right_padding				 8
bspc config focused_border_color "$CYAN"
bspc config normal_border_color "$BACKGROUND"
bspc config active_border_color "$MAGENTA"
bspc config presel_feedback_color "$GREEN"

bspc config pointer_modifier control
# bspc config pointer_action1 move
# bspc config pointer_action3 resize_side
# bspc config pointer_action3 resize_corner


#BSPWM coloring
# bspc config normal_border_color		"#c0caf5"
# bspc config active_border_color		"#7aa3f7"
# bspc config focused_border_color	"#bb9af7"
# bspc config presel_feedback_color	"#ff9e64"


bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

dunst &
fcitx5 &
picom &
udiskie &
copyq &

feh --bg-fill -no-fehbg ~/OneDrive/Wallpapers/tokyo-night31.png
# dwall -s tokyo
