return {
  { import = "plugins.extras.coding.pairs.mini-pairs" },
  { import = "plugins.extras.coding.surround.mini-surround" },
  { import = "plugins.extras.coding.text-objects.mini-ai" },
  { import = "plugins.extras.coding.comment.neogen" },
  { import = "plugins.extras.coding.comment.mini-comment" },
  { import = "plugins.extras.coding.motion.mini-bracketed" },
  { import = "plugins.extras.coding.motion.nvim-spider" },
  { import = "plugins.extras.coding.move.mini-move" },
  { import = "plugins.extras.coding.jump.leap" },
  -- { import = "plugins.extras.coding.jump.numb" },
  { import = "plugins.extras.coding.join.treesj" },
  { import = "plugins.extras.coding.incdes.dial" },
  { import = "plugins.extras.coding.symbols.symbols-outline" },
  { import = "plugins.extras.coding.rename.inc-rename" },
  { import = "plugins.extras.coding.refactor.refactoring" },
  { import = "plugins.extras.coding.yank.yanky" },
  { import = "plugins.extras.coding.treesitter" },
  { import = "plugins.extras.coding.complete.cmp" },
  { import = "plugins.extras.coding.complete.supertab" },
  { import = "plugins.extras.coding.complete.luasnip" },
  -- { import = "plugins.extras.coding.complete.cmdline" },
  { import = "plugins.extras.coding.ai.hfcc" },
  { import = "plugins.extras.coding.ai.copilot" },
  { import = "plugins.extras.coding.ai.tabnine" },
  { import = "plugins.extras.coding.ai.chatgpt" },
  { import = "plugins.extras.coding.ai.neoai" },
}
