return {
  { import = "plugins.extras.editor.explorer.neo-tree" },
  { import = "plugins.extras.editor.search.telescope" },
  { import = "plugins.extras.editor.search.ssr" },
  { import = "plugins.extras.editor.search.project" },
  { import = "plugins.extras.editor.fold.nvim-ufo" },
  { import = "plugins.extras.editor.git.neogit" },
  { import = "plugins.extras.editor.git.misc" },
  { import = "plugins.extras.editor.git.diff" },
  { import = "plugins.extras.editor.keymaps.which-key" },
  { import = "plugins.extras.editor.runner.code-runner" },
  { import = "plugins.extras.editor.terminal.toggleterm" },
  { import = "plugins.extras.editor.terminal.flatten" },
  { import = "plugins.extras.editor.debug.dap" },
  -- { import = "plugins.extras.editor.runner.competitest" },
}
