return {
  { import = "plugins.extras.lang.lua" },
  { import = "plugins.extras.lang.java" },
  { import = "plugins.extras.lang.csharp" },
  { import = "plugins.extras.lang.nodejs" },
  { import = "plugins.extras.lang.python" },
  { import = "plugins.extras.lang.cmake" },
  { import = "plugins.extras.lang.rust" },
  { import = "plugins.extras.lang.docker" },
  { import = "plugins.extras.lang.bash" },
  { import = "plugins.extras.lang.clangd" },
  { import = "plugins.extras.lang.typescript" },
  { import = "plugins.extras.lang.markdown" },
  { import = "plugins.extras.lang.http" },
  { import = "plugins.extras.lang.ymal" },
}
