return {
  { import = "plugins.extras.lang.lua" },
  { import = "plugins.extras.lang.java" },
  { import = "plugins.extras.lang.rust" },
  { import = "plugins.extras.lang.nodejs" },
  { import = "plugins.extras.lang.python" },
  { import = "plugins.extras.lang.c" },
  { import = "lazyvim.plugins.extras.lang.go" },
  { import = "lazyvim.plugins.extras.lang.json" },
  { import = "lazyvim.plugins.extras.lang.tailwind" },
  { import = "lazyvim.plugins.extras.lang.typescript" },
  -- { import = "plugins.extras.lang.yuck" },
  -- { import = "plugins.extras.lang.ymal" },
  { import = "plugins.extras.lang.markdown" },
  { import = "plugins.extras.lang.http" },
}
