name: "Check Flake"
on:
  workflow_dispatch:
  workflow_call:
    inputs:
      ref:
        required: false
        type: string
  push:
    paths:
      - "**.nix"
      - "**.lock"
      - ".github/workflows/check.yml"
      - ".github/actions/**/*"

permissions: {}

jobs:
  check-flake:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Check Flake
        run: nix flake check
