name: "Check Flake"
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "**.nix"
      - "**.lock"
      - ".github/workflows/check.yml"
      - ".github/actions/**/*"

permissions: {}

jobs:
  check-commit:
    name: "Check Commit Message"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run commit message check
        uses: ./.github/actions/commit-message-check

  should-run:
    runs-on: ubuntu-latest
    outputs:
      run-check: ${{ steps.check.outputs.run-check }}
    steps:
      - uses: actions/checkout@v4

      - name: Should Run Check
        id: check
        uses: ./.github/actions/should-run-check
        with:
          prefixes: "chore docs"

  check-flake:
    needs: should-run
    if: needs.should-run.outputs.run-check == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Check Flake
        run: nix flake check
