github_token: ENC[AES256_GCM,data:j8U3QlAgSqYhs7UVBchTsySIt6tLNl+YXD+WC8vtFtSNTQcPT51I8Q==,iv:hX46cvpE2SkGUyX05NJAW1SdpAQdCNuGbOdiyr+SOmQ=,tag:VmNbKa6fWN7kgtm4pBBolQ==,type:str]
atuin_key: ENC[AES256_GCM,data:kwUbSXrDLZIEoeXH6J8zbyM5DATJ+JOGgxCs/m3zJXFCi/3N3SSGxZrUh0G+2xHx1ngQDLbCamgGEHkadp7Cga6skQU=,iv:OsfsjJjP72S0U5GKaXTYnNCfN6FJE7aA8JTGMRJXbkU=,tag:8k9SCaImvGP7cVMzwKPkog==,type:str]
atuin_name: ENC[AES256_GCM,data:U3Oh+3RNcuD7XA==,iv:RTqQBH7ejCFw/pQ/pakU/waBbENCZXNfiO9T3Wi3HA8=,tag:iQnLt1uiVxMcpqi5AxCZ6A==,type:str]
atuin_password: ENC[AES256_GCM,data:q+CAP9XDdQDdje4=,iv:cSNKLv+zGFkEw0XsIcK7zo6pzIrEfi68XVZaXi9K7hE=,tag:rwZ/jCM7hLA7wZOxYrw2kg==,type:str]
atuin_keys: ENC[AES256_GCM,data:M2s/dvOERFPSTxWsDlwv85IKsSEPVXQIoUplKk0hB7phLfk+658hgsW/Ur7CU76Jlg5o8dS4u3S5mGEYIg7zD8EgVOD5iVe+FNZNyZsaKpcepT63d+YF3VQS0I/gwWmCg1pX6BBGucoEqLzvo1HtGINYadHOd6AxhJIfrumJTIgMPkKMdPQzqUHJNv8IOGk=,iv:5Tm1JSHWkf6ByhqDx+lgaeBxDj7EJtRhWzYU40vB0vE=,tag:f7MnZ0IpPyfuxBWEe8uRlA==,type:str]
spotify_client_id: ENC[AES256_GCM,data:m5Opgcknn8z459WyNDY6AswtmtCzzlDz6VnvwEMGHA0=,iv:HpK0rFvU69qZupq5d2q2gxW21cPzQKKklasTcpLiBKI=,tag:19iGGtlyVircVhS4EQf0iQ==,type:str]
u2f_keys: ENC[AES256_GCM,data:i2cXtJIsnbRyc3MxZwJTcBmQ5UvMu9j8IO7RDc4IIRrOD3SYdJeUwptMepsCjGzlb/0RvzYtn0NAs7so9hi3uMl+WWLekbQ6JDC+eJy0gvMrYpWwh39UbdKRzrLS72Tjoh/wkoF9PPa24FpfgVUw2V/D7p2C2/x9QY7iUxmxuxTZe9sHWd1L67lA47qQuAu+YG7XuwEpAqpeZ5j/2++XivkSXxUefLLz8c76m6J6JrIDeLmXLJLPKa5EfEgVeoea0XPT7XxVtgLOs4cI8PRNS5/iAtEYMCIPx+JHZAAYq0PjaS22+x2yrC2QwWVxqy1QjJnUNFGRlEGGOhoti0gLsbhv+YuTIWiGOnbMlACYG7QhPPYfLchbX/D3SZSuNh6t4wTJgs5xa1bz0vomCjhgZMR6DbItjBAMZcdWdXfBEDYWR8JZMnCwgQikeFChOna8EE8UbBQ1cpAnRp8wKSm7ljWaPBgJ5cqIu6IoCU3ZoAXRgBKDw+Ux5b6pb7ra1bywwh4Cab2WTWVmZItpiAoAgsLYB6/pZg+AgUzU2ePSvFbzeTbyWgRYLJr0LdkGFy/dFHTQHz/c7TArUQtlDCTKhsGPxUvqu4QzqfyVT/sI70lUSZ7S4NiB0zlu1o1x0m3rtO7SWVb8P6ojdoius8GpZxgfO2f9i1x62em08eyUYR/MpUEGywlO7jEUPkQEpqpX3SsSWPIvn07OFda6b+OOk4TCZIf+498ETq7HVFVuEPi4mrgMSPl3bDme5J3jl3avBjciB/KYvEwZg4pHxA==,iv:tazR/b5p7Pmo2ygD449n/JdPBBysBILiYk0TEO3qJZw=,tag:QlOrlfT5pKYreAP4GrIPLg==,type:str]
sops:
  age:
    - recipient: age13srgr0k8nkwfh6yuptk9g3ly9aslsatmav4cvje04z58lp8d3d6q0d9g6j
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnbHhxeXBGWk9aZkdKSVg5
        TElOYTJ2SnFYbUR4dm11d284SHhxTGZ0RlFNCkRIeGQ5NjdWK3NtRnAvZlVqQisr
        bm5xWmtGb0dXL0hVNUpCbERGRk5RaGsKLS0tIFAvZzRzOUg0UWJYS2RwSDFXUTBi
        dXNTNVBkUG9tMFVjU3dndUo2WHdOancKSGlgBVDkYSkU4H7mTyy5UwAoiCkdPUQB
        AR20nK1ybOnQ9X1PfddHZPPuuyHqq7Bi8mN87Js/DFA6RnY9zjAq5w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-08-16T02:25:37Z"
  mac: ENC[AES256_GCM,data:9M6iuHUFuRT5+SYbwVGYOFlZSjQTzlrikOGKeDPKUztAJCsO8OrrnvlsZ3duqUYo20B1WoGqe8HqwlmnpQ3IYADGdhpG/I0Caz98uVJyhgOHX4NIohLwqQNT+nezQ5r3oYvHMHOKdA6ufDuTybi8JQeIa0jBtGqUSrbZ5i1myI4=,iv:D4diaEij8z6Rim7dkD5xa3Wm1fF5r4UZjzxs/3iAp+M=,tag:8BArTZ0BMrA1huGHfVCr9A==,type:str]
  pgp:
    - created_at: "2025-08-16T02:41:55Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hF4DK+ZqT54JVUESAQdAimYhZepvCnaFMiXAmHcIyrg4cRcJhdXj22+dFFFAn2Iw
        0nZ9POsuOfmF/yT8Bh9F8s/3FFORt1P9tynkd0V+UZ43zvtJCEcDzchaHxvpw18A
        0l4BBsaf7vnUHwE0W7s8uuvWnCPMK2PhPpxH3W8VQ8HcOIiWf5eJmrm5Ffxs1W14
        khwFLR3udv+LLXmV+nESIbplRIxaJnMAJAn37k7KGIiqRQjZwbhNCq/Wp1WtLax0
        =XCAz
        -----END PGP MESSAGE-----
      fp: E23E274D412D4C761A871B1E776C7FC245E58F55
  unencrypted_suffix: _unencrypted
  version: 3.10.2
