github_token: ENC[AES256_GCM,data:AkskJhQJHf3EDoEiIVNhwnlNiRiZ3NZSgw4Jx8bPSYC1LGSipSMJEg==,iv:hX46cvpE2SkGUyX05NJAW1SdpAQdCNuGbOdiyr+SOmQ=,tag:zH5pJN3Hg9iJCqsAXtiNqA==,type:str]
sops:
  lastmodified: "2025-08-14T23:56:01Z"
  mac: ENC[AES256_GCM,data:zpU2FFghvSBUQdgx5jZPjSWeGE5opwxVe1Dv4ntGkzLT+/uY7JjDtWeF+tHdEfNdQxDIcNWcPb9V+GzRWZ+VoZzKHhmLxPtvgb30SIaUz7q7mJ+lmWmQREEMoczPpc96WeR1QV922S4jkcF+/0OLUVLs469AlgH2teAceOKRJZE=,iv:jxsBNRbW23osg2X8f8jGh/JDt1+HmKhRBDPvzrJZhrk=,tag:1CcEC9Z0/5Rw4sRJdM7lcQ==,type:str]
  pgp:
    - created_at: "2025-08-14T23:14:46Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hF4DK+ZqT54JVUESAQdAqzLaLkATea1mQnLgqKh5RBEXhneMsJTX7PqncoEbaisw
        UinrlHdz0oXD7OnjQ+H5jHQz72fhKrXFXNWAu2G8jTLL91Dt201uQOmnNkf3AchM
        0l4BvYxJ6xg4RCddWMPLg6WZDVxQtWD73sJuJGYbkfsypZ4x1Ui2Kzhc9bJyuBx/
        8EqWUeyBQJarLUy5CjpJ5SPaT9flWcvQqfvr0tkuF30vuRx16r1VzQGAfnA0MrAt
        =2WLw
        -----END PGP MESSAGE-----
      fp: E23E274D412D4C761A871B1E776C7FC245E58F55
  unencrypted_suffix: _unencrypted
  version: 3.10.2
