github_token: ENC[AES256_GCM,data:AkskJhQJHf3EDoEiIVNhwnlNiRiZ3NZSgw4Jx8bPSYC1LGSipSMJEg==,iv:hX46cvpE2SkGUyX05NJAW1SdpAQdCNuGbOdiyr+SOmQ=,tag:zH5pJN3Hg9iJCqsAXtiNqA==,type:str]
atuin_key: ENC[AES256_GCM,data:2+fYauWIUjKQ+uEwt/n1SWwFcDoeYgrYdzu+3w3sfNKH/ZCl8bix30lJ8xpw1mWB2YheeeETUE1Qm3M9aGsNw5tkg40=,iv:OsfsjJjP72S0U5GKaXTYnNCfN6FJE7aA8JTGMRJXbkU=,tag:6cSFcpRiLZwBkNVGi34wqw==,type:str]
atuin_name: ENC[AES256_GCM,data:PdUKTabQHFdUAw==,iv:RTqQBH7ejCFw/pQ/pakU/waBbENCZXNfiO9T3Wi3HA8=,tag:1PSqF2a03gmsQqGa6ZdExA==,type:str]
atuin_password: ENC[AES256_GCM,data:TExiYdsRv3qxc+8=,iv:cSNKLv+zGFkEw0XsIcK7zo6pzIrEfi68XVZaXi9K7hE=,tag:y/ft7rrsU1MipUyEzROHDA==,type:str]
atuin_keys: ENC[AES256_GCM,data:WRBt1JC48/4GJ4SGKm2bVbQLgV5oyfwMFwbTSRqFF1TeK/jISJzTkXggLNNdI6IaxvGjvmVwvIjEhKfgZX28+I2NWa7SLWoQ1tV1+BvT9dijrJGYkplCZJ8Jhp+6L30V8bnvoXN4j/3OvU/dCfQ80xZVdwYdaT+epq5KPIjFnxZpKrYH18wCG/0ojz4Z6Sk=,iv:5Tm1JSHWkf6ByhqDx+lgaeBxDj7EJtRhWzYU40vB0vE=,tag:jEiZjhxxY3uCCTnlLzQ10A==,type:str]
spotify_client_id: ENC[AES256_GCM,data:qfZKNkhVPMeixgIgjDhsu1CRzQL/VHTju9b0lBlO0dc=,iv:HpK0rFvU69qZupq5d2q2gxW21cPzQKKklasTcpLiBKI=,tag:tI+o3QXgwsV8uAGrDPunyg==,type:str]
u2f_keys: ENC[AES256_GCM,data:Qy7FWGEEy+NYhE6VsSQxUps/cALErJsKr26w12uyqcHdTgioCg8DDNQgiMUsYG4DATFqxMfjBgbqw9D+KvZ8DpW5GyG8BNVh3jwvSSL7pIxsMqLLda4NUWULHCouJ1reIxa5HS15Oe1wQbi9ML1bVwV/dGtWYsCWUv5jEN4JZNMhqBWL8ybvIHI1mBMEoOtenk1TMR+eNWWW39MmmWHMDrVFspsaGZHpMPwhcUidlnmeQBFEPaXi5GxQw4ZNC20FUTk/5teZd27UzWTT7vKtZRnwI3RNxkZ1j7hKvAorqpuUnfQKgDN8J4IVWdztVkdQbbaFjX2l8MYTdLtfhjfpkE4JfgoGiwPv7QP1jut0HEvPB0NJemZyewZdVtEWWq6W+6qdoIApz5EfOps8mRLceOxdVT8EocZik5x8e/1dPxjnWulVZyefXgbNGzR0aiGD+fm5oqdcOOgg4ee8z0Aw/SH6bjYgw4dsQW+lvwiv6T2pv3ty5/7WIG3mTbooeUKSy1J1m784STyKHBp/VHCfYgHrMG6fCk1Rh/iu3k6nXjVr+ZRxcPtGrb7LVLQ+TVPHwUWz3s3SHlS4nPJUkdOR1EAEPcmRAAs0JfWSR8jx3t/ouuhxUd9IuCWWarPOLed0mrP2Me0kRTCW9TAPU3dmVh/3M4I/6x/+DFvdhW73mNdQ9JOCd6UuOxPb8KQnbhd6fkuW4J+d4aNNaToDaD03vyHv7r6TL0Fck3WjpkC2tAQTSDgJFmGfYvkHeXmFUutBzvugPoqedueqDu7HmA==,iv:tazR/b5p7Pmo2ygD449n/JdPBBysBILiYk0TEO3qJZw=,tag:otQX+X/V7vheXm9An0UGvQ==,type:str]
sops:
  lastmodified: "2025-08-15T23:01:04Z"
  mac: ENC[AES256_GCM,data:DFnqoUQXtCLYWpD07dztF86ElV3ruSURyjo0R54Kx6kXY+fltA0XvUJOy8tk6pJZBxLeMzWjsSeDhn5u2yiGXWswHLkEEscV+BeOCUrVbzColom9MpmwiUUl48zZ3ytLBlZsBMWjD92wVILNVVwMOvXwIr3WsIrH0cEdI1xBoGY=,iv:RcUKwI8KLZI+DuNigOABVo6R3RrYlmeWINIIanNB3oo=,tag:p/AL+rysqg2HhmJp9esxfQ==,type:str]
  pgp:
    - created_at: "2025-08-14T23:14:46Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hF4DK+ZqT54JVUESAQdAqzLaLkATea1mQnLgqKh5RBEXhneMsJTX7PqncoEbaisw
        UinrlHdz0oXD7OnjQ+H5jHQz72fhKrXFXNWAu2G8jTLL91Dt201uQOmnNkf3AchM
        0l4BvYxJ6xg4RCddWMPLg6WZDVxQtWD73sJuJGYbkfsypZ4x1Ui2Kzhc9bJyuBx/
        8EqWUeyBQJarLUy5CjpJ5SPaT9flWcvQqfvr0tkuF30vuRx16r1VzQGAfnA0MrAt
        =2WLw
        -----END PGP MESSAGE-----
      fp: E23E274D412D4C761A871B1E776C7FC245E58F55
  unencrypted_suffix: _unencrypted
  version: 3.10.2
