github_token: ENC[AES256_GCM,data:mKV9xNWgIVsrYA8eCyPZJ68YcwtdqvMe3zMrXfJeNH2yP9/UMYRH0g==,iv:hX46cvpE2SkGUyX05NJAW1SdpAQdCNuGbOdiyr+SOmQ=,tag:AGVzyOcDDJOyMfEGohJ3Sg==,type:str]
google_cloud_project: ENC[AES256_GCM,data:BV9O9hbPov9dSvYo246Oq77LcNkZIg==,iv:zlVmkmkAiP67u/Y1SiVlechJcKwlAglM3Myp31ufUcE=,tag:rcUuxb3iN6qsnbnkqidZTQ==,type:str]
atuin_key: ENC[AES256_GCM,data:jVOoGX0XxfnKJTS6ucuKzIY6Kqd7z1B0LwQTCoZ9D0KCUXjLSmUqAUFuuBwi4ZuT6VWgLf6Pj7BXY+A7Qbf1vCqO44s=,iv:OsfsjJjP72S0U5GKaXTYnNCfN6FJE7aA8JTGMRJXbkU=,tag:rCU29FmRxWu1/eHr9KM85g==,type:str]
atuin_name: ENC[AES256_GCM,data:8vyREY9pezslrQ==,iv:RTqQBH7ejCFw/pQ/pakU/waBbENCZXNfiO9T3Wi3HA8=,tag:CDo1M9ohZLYcJ4dpCzGCuQ==,type:str]
atuin_password: ENC[AES256_GCM,data:U2em7gS1mpOZe8I=,iv:cSNKLv+zGFkEw0XsIcK7zo6pzIrEfi68XVZaXi9K7hE=,tag:jKXqKeaucr0mDfHZqooPMw==,type:str]
atuin_keys: ENC[AES256_GCM,data:hkhWo0LX5HA6m2OTkY+T44TfDJI5nglG7Sp3w/hJ1/eo39c0N8PEEnUplXqbq/r5U9CHVxwgJ7a8+YyP7FdRjndn3HDWrM+gPt2BZRLKaR9npY6I9lk2eLtwygr18tkH/ftSZc24HWPIwqvJj5GGep6dbXA588zRLla/qu4MX4OYq7+cDsmIkbCW7gTHxeY=,iv:5Tm1JSHWkf6ByhqDx+lgaeBxDj7EJtRhWzYU40vB0vE=,tag:0neq7qIcBEEA5olcwDfhew==,type:str]
spotify_client_id: ENC[AES256_GCM,data:sevOT0NlnAEVlKf0TaItkzONHauTYsuLly46jBDKBn0=,iv:HpK0rFvU69qZupq5d2q2gxW21cPzQKKklasTcpLiBKI=,tag:ViXEASfng8j6jcw/SMxH2A==,type:str]
u2f_keys: ENC[AES256_GCM,data:s7V+ocpN8UyOEGePIOIzOJY6tvpKuvJKxLmJSkgthGjyeeAQ5BkasCuTtrRF9tnjaG8vczpc6n4AQA/yEChr74QsbEJ5UybexjQwyfbk0K4il3HwC/eNpT4WS4Fo1g4YfF5+tvgjdtLnNHH5699s50ca++hTaXqxjyCW/pjYOT7EsTXoPdXuxdf2MiAe/2ewnmVUFBKChn5R1llJWe95XU8bl3KHKyUfc6a260xV3WXSRVtxKhrPEqs1B8KBkVluIQRjQn4R3dFm4w6dLzB1HkfGpCAIrwXZPwgfS2aEaV6XLrTbM5KEfJzk/VodDzxH3SWqB3PezkmPsvh0Ej1ApLVC6UnBDr6DnRG3SUfMi1CEcyvuy3HAJ9ApIVirDioHXR7UZPX1RK3/3M7N/H+N+LS1WvDMrn+SkiXMrzy+XHsciXpUdil0Wf915mZExlYU2Lf8O3mI2mLAdkC07XIZvQRVVcykf2Jty3KOTgck9L1qp8E5/MPMnYr9y2Xb3JnfmB+VTVMlQlNCItl98Lj2sv+SgdWuL1F5ip0lYausTTUJ9kCR1wtoTM+NvgkupC9KwIPtBq6p80n+AVXY6XQcY8kXS/IbQVKqIGb7Zrgx23IZ6uZWsMixH1/TJcLxhoqlm0PcbwfM107YSwdJ9YjiGl/UUso5NtONZSiJMWsNfiSALYxC4/ciyqbvR0kdzp2sCp/rBPYGXYuHJm006CBx0mo/0txnARtNTWFOpWOev2ell/uCcKth8WMVxt+Mgd/XusAFAhuD0fdsuveGHQ==,iv:tazR/b5p7Pmo2ygD449n/JdPBBysBILiYk0TEO3qJZw=,tag:NdewtCd/mO5PreMPi8E3TQ==,type:str]
sops:
  age:
    - recipient: age1dru9s2hakwc4zjzh64z35nkt7uemgq4xc0vz5v5m8s2juy0edugs5esp5j
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1ZnlqYmIyeHVlNTgxNElP
        RTJ0R1NrRVhJQW9pNlN2K2pjOHF1QWtGcFcwCmlMVjVObUMxbzd3VnpaQ1dsdXUv
        eWZtb2hFZytRaXpJLzh1dHlscU5DaGMKLS0tIDF6c1oxY0hGcTNESUY2bVIvU0dj
        ZFZibmFpOEZjb2piV0l5T0VpUlQ0Q1kKopW5oSD58hLXzwH4opaQQLr419broY+L
        SlHlPoATJB9G5k//xBfe3z2ZcO+vPO+v5cOxkMyAJ5WPxuXpR1F8Gw==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age13srgr0k8nkwfh6yuptk9g3ly9aslsatmav4cvje04z58lp8d3d6q0d9g6j
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1UnQ2T0VHVDVsOUZPdHdE
        REJqSU1CU293Q3RyWHR2RlQ0SlY3U1dlSUcwCnBaeEJmQXlKSGJnVlJnNjB3am1I
        YU11eEt5MHZaaGN1SUJSNWs0TW82YUEKLS0tIDhXUGNMajZFbGdZUlZIRHE1QTQw
        dzFyTXFjdzNhNzFlVUVJR2R5Nk1qZmMK9fgB6TuqNMLNYCeOy2xaRtYRCTtEA4Rw
        ysehwLGENFL0NmpUYt4CeV+YYtGscxOQxrgbKvQR7Lwu2ZEOVvgZuQ==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age145r5u0hvnd6xnfgrhgxs0ayp205jsrc2h7aakl4dzmhr78ek9fqs9jfwd2
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0R2x1Sk1OdG5HS1VzaURl
        S1NPdFNwVGk0RjZVMk9NL1lhaXRyU2FtM3k0CjVTNmZFNTZJQ2x2RkxGWmlwQmo5
        UUZURXhOZHhyWlZHZmFiUEYrL0JTZ0UKLS0tIDFXRG5SdUplRWlSOExJVHZ6aW9Z
        UDlFUVRQV1NDeVVLRjUyaERia0RhNTgKIrGgS4yPj7nOfnQwOyKbrK2wdK90FTT/
        WZuuBr3oviADs4o2imSTmP8CcsNid6dJo/yRxIAu0u0gentuxL8B2g==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1ezm8h5js9rl3s23d3xp9ngsapd5anxn7lh8gcd4pafd4ck0alu5qju0lt8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2QVFVYzFicnB3ejc5TWMx
        dXF0UVI4SzV3STZzNkpaTm8zZnRNcHhrM1RrCmJIbWVxTnMzU1Bwc1ZMZFlmMjE5
        Q040Ukt0WDJvNnpKRmhqZ3hvNGdDcUEKLS0tIC9zOUlUcDZYZW1MRVVBZS9ISDhp
        ZUpaZ3U2cURkblZva0tUSmxsNnozSkUKVx6m5cpyBk7tA8/6Rkg48BCLkvhGt77D
        gC7vlfNaDyzI1dOwdAjP57KS05kGutrOgfb3PtDgmc16GsuK6Ta5sw==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1f64lg3datsj9l5gq6ca2kuczzg9l2upu0ukavk3ykry5z59c4qnqtsdpgc
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmWWdXaXNCRTQ1WGhrdlM2
        NWxrTkdkS2h4aTFkem9hY2lyVlhqMlZFV1JrCnkvTG1DOVdBVzA5V1A5RmUxQ095
        ZkFmYnE2ZTFDTWxvZVJOaGhNcm5GSlkKLS0tIERzT01mOXEvR1lJdTdadFZLRndo
        dXR1Yi9wc0VLeG5leGZUZ0pHcEx4TmcKGdScWLWoS45nA6h9t/BwmaIshnNBgACP
        F8hO57OzJZSf3vmWkSPN5SlVFoyg3lW0SomBwCCoaQZicwsSDYGnzw==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1m8f0m489vql2p7l4a80ehjh0ae4zgwcnjzv8ngjrsg957yjlcyrq35nvv8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjcVhhR1Z1cDZIZUhPRmZw
        SWFHZEwrS1hXL2QrREQxVmlsZHhjUUFxWkZRCjdLQ3luNUMwa3pSN2daNThTY080
        ZlB1ZDRCaFB5eW9HaEk1SmF4ZFlkY28KLS0tIHJVS3R2NHk4OU9vMmdIRTlXUmlP
        TjJRSzdYUkdmRnV0Um94ZGpqbVZnRTgKl191uqwP5g/Y6cBLErv3tV6OtyBwdrBd
        qfS28rk2NjZJjDrCIpQ5psnem/wcXsFLINIudOw3WUQXjKqZZryEpw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-08-18T23:05:48Z"
  mac: ENC[AES256_GCM,data:/cHXJIi65/4y5lgh7khAb7u8X7tfsSyyONfyTZ5TDcyR8wvLPJLUzC/7WI9I0ol34avSDkKdyjlw3uLTS6KSEqt3Ew7yIc5OY8E1o6CbY+gyMdHYGy+fcHdtqCFK0JAo6nc81zy674y7axTk+HjLCB8uCyHobmsx0AxqkGcy6bA=,iv:xeVwD/BQ28eXvovFUMIYiWd3hhajGpa46HvVcDeT5hY=,tag:np6a1w3UQqy/iwjQU8LPdw==,type:str]
  pgp:
    - created_at: "2025-08-18T23:56:19Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hF4DK+ZqT54JVUESAQdAr+GxI7C/j9q9opmdxsDwbN//DiqdzzudY8ADjpmp804w
        4emGL2HPUwP3hadIFvioZtGx6Ja28pzHQ2vUhwaLVcbR0adKl3VGjy+o97GkUeJU
        0l4BpSig1mcSDpqjs+bbTV93LTppYfaHBeI1+57cNq+1icq1jpsXjqtSQb3c9Mi1
        Mw8MyaPIesKm5xW7OJ1fYIc48mLVF9jo2JrS/MnmMCAfhuVktYtHmV+OvW396kA4
        =fMxK
        -----END PGP MESSAGE-----
      fp: E23E274D412D4C761A871B1E776C7FC245E58F55
  unencrypted_suffix: _unencrypted
  version: 3.10.2
