github_token: ENC[AES256_GCM,data:mKV9xNWgIVsrYA8eCyPZJ68YcwtdqvMe3zMrXfJeNH2yP9/UMYRH0g==,iv:hX46cvpE2SkGUyX05NJAW1SdpAQdCNuGbOdiyr+SOmQ=,tag:AGVzyOcDDJOyMfEGohJ3Sg==,type:str]
google_cloud_project: ENC[AES256_GCM,data:BV9O9hbPov9dSvYo246Oq77LcNkZIg==,iv:zlVmkmkAiP67u/Y1SiVlechJcKwlAglM3Myp31ufUcE=,tag:rcUuxb3iN6qsnbnkqidZTQ==,type:str]
atuin_key: ENC[AES256_GCM,data:jVOoGX0XxfnKJTS6ucuKzIY6Kqd7z1B0LwQTCoZ9D0KCUXjLSmUqAUFuuBwi4ZuT6VWgLf6Pj7BXY+A7Qbf1vCqO44s=,iv:OsfsjJjP72S0U5GKaXTYnNCfN6FJE7aA8JTGMRJXbkU=,tag:rCU29FmRxWu1/eHr9KM85g==,type:str]
atuin_name: ENC[AES256_GCM,data:8vyREY9pezslrQ==,iv:RTqQBH7ejCFw/pQ/pakU/waBbENCZXNfiO9T3Wi3HA8=,tag:CDo1M9ohZLYcJ4dpCzGCuQ==,type:str]
atuin_password: ENC[AES256_GCM,data:U2em7gS1mpOZe8I=,iv:cSNKLv+zGFkEw0XsIcK7zo6pzIrEfi68XVZaXi9K7hE=,tag:jKXqKeaucr0mDfHZqooPMw==,type:str]
atuin_keys: ENC[AES256_GCM,data:hkhWo0LX5HA6m2OTkY+T44TfDJI5nglG7Sp3w/hJ1/eo39c0N8PEEnUplXqbq/r5U9CHVxwgJ7a8+YyP7FdRjndn3HDWrM+gPt2BZRLKaR9npY6I9lk2eLtwygr18tkH/ftSZc24HWPIwqvJj5GGep6dbXA588zRLla/qu4MX4OYq7+cDsmIkbCW7gTHxeY=,iv:5Tm1JSHWkf6ByhqDx+lgaeBxDj7EJtRhWzYU40vB0vE=,tag:0neq7qIcBEEA5olcwDfhew==,type:str]
spotify_client_id: ENC[AES256_GCM,data:sevOT0NlnAEVlKf0TaItkzONHauTYsuLly46jBDKBn0=,iv:HpK0rFvU69qZupq5d2q2gxW21cPzQKKklasTcpLiBKI=,tag:ViXEASfng8j6jcw/SMxH2A==,type:str]
u2f_keys: ENC[AES256_GCM,data:s7V+ocpN8UyOEGePIOIzOJY6tvpKuvJKxLmJSkgthGjyeeAQ5BkasCuTtrRF9tnjaG8vczpc6n4AQA/yEChr74QsbEJ5UybexjQwyfbk0K4il3HwC/eNpT4WS4Fo1g4YfF5+tvgjdtLnNHH5699s50ca++hTaXqxjyCW/pjYOT7EsTXoPdXuxdf2MiAe/2ewnmVUFBKChn5R1llJWe95XU8bl3KHKyUfc6a260xV3WXSRVtxKhrPEqs1B8KBkVluIQRjQn4R3dFm4w6dLzB1HkfGpCAIrwXZPwgfS2aEaV6XLrTbM5KEfJzk/VodDzxH3SWqB3PezkmPsvh0Ej1ApLVC6UnBDr6DnRG3SUfMi1CEcyvuy3HAJ9ApIVirDioHXR7UZPX1RK3/3M7N/H+N+LS1WvDMrn+SkiXMrzy+XHsciXpUdil0Wf915mZExlYU2Lf8O3mI2mLAdkC07XIZvQRVVcykf2Jty3KOTgck9L1qp8E5/MPMnYr9y2Xb3JnfmB+VTVMlQlNCItl98Lj2sv+SgdWuL1F5ip0lYausTTUJ9kCR1wtoTM+NvgkupC9KwIPtBq6p80n+AVXY6XQcY8kXS/IbQVKqIGb7Zrgx23IZ6uZWsMixH1/TJcLxhoqlm0PcbwfM107YSwdJ9YjiGl/UUso5NtONZSiJMWsNfiSALYxC4/ciyqbvR0kdzp2sCp/rBPYGXYuHJm006CBx0mo/0txnARtNTWFOpWOev2ell/uCcKth8WMVxt+Mgd/XusAFAhuD0fdsuveGHQ==,iv:tazR/b5p7Pmo2ygD449n/JdPBBysBILiYk0TEO3qJZw=,tag:NdewtCd/mO5PreMPi8E3TQ==,type:str]
sops:
  age:
    - recipient: age13srgr0k8nkwfh6yuptk9g3ly9aslsatmav4cvje04z58lp8d3d6q0d9g6j
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjMFVoeWg4MkVGdTRZQncw
        bEJSTmpLeSttSjJZajZCYnUvNDA3QlN2RFg4CnBja2dEU1dsVS9NVUhrM0MvQWNG
        UUtraDZGbk96U0F6K0hJM0MyNldCRFkKLS0tIDhrSEk3dGx0RHJQS1FiQW8rNWpQ
        d0k1VE5MOWlLSS9MVUFpbmo5cC9HWlEKGvDPP87M8IkFW5oi3MMPvxYUvISHmf1u
        D78QChQrhclha50lOeQcyftcMVNMcesggwzemaxoyIcsX43hR18F3A==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age145r5u0hvnd6xnfgrhgxs0ayp205jsrc2h7aakl4dzmhr78ek9fqs9jfwd2
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4M25HM1R3dS9KSi9ha292
        cU1vT2hxWmpleERvaFBNeTNaUEFCVG4zZkZJCkcxUVR3eDJNU1RMY3RiSGs2ZW5x
        NUtQUm41WERwVm5NK0FEWnV2Mm95N2sKLS0tICsxZTlFeVpMTThmUWVDRGNpSi9C
        bnBWbTZ5MG1XcDZ6UFhyQzdEYTVwOGsKQ/nOYfOQ/IEQF+9Dj6d2yR18NliXr9FH
        NQsh0X5PvywQJbnJI44yxbFv+SSC66LXLff717/UXE7fcCYJ2JdhHw==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1ezm8h5js9rl3s23d3xp9ngsapd5anxn7lh8gcd4pafd4ck0alu5qju0lt8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4UHBoOGdnak5RRHUzSTZn
        eHJiSDI2MkpJYlpxSWg1WlgvUW5zaTExVmtNCnlsZzhNL2NaSXg0SnFDcE9LWXRT
        cFN3QTVtaXFXM0dweDBsN1NPZlN1ZlEKLS0tICtJdmNPbzBNZ1hINktXdElzWEtp
        ZzdrUUZIUlpZQnFHS3lZMVM3emRrelkKWQ01WHd+wv/5xChYiXPeBwDYyCMPaKpB
        vaTHLQEcyNr3cHKzZr8uHUp9upoeDSctL7n5Q9kyoHb1o2GND6WrkQ==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1f64lg3datsj9l5gq6ca2kuczzg9l2upu0ukavk3ykry5z59c4qnqtsdpgc
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYeDBSaCtYUEIydlJtZVZL
        NnppZEdObWVqVlVkc29xMTd6M3VGdkJpNkFVClhDdVVqUWg1RXU4RlgrMENxaWNZ
        Zno5QTBCa0krd3h6Z1g4NXN1dEFibEUKLS0tIFg1eXMxV212WkxLL1lYMW5MQlN1
        WlJSYzZPR2k0RnZYbWVGL2t3NlczcnMK7f9+FQmOKRKNiea/IdXMl7JCz48tM2or
        xCIKS8FObxCKurCdt7GIdM8P/pyTbqT+8BFZFDlGwaE3EsovStLB6A==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1m8f0m489vql2p7l4a80ehjh0ae4zgwcnjzv8ngjrsg957yjlcyrq35nvv8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoWGY0aHJuVFo5NUZRVjcv
        N3BjbnprTEhXVS9nVzlDV1RVaE4zTnpKYW5jCkUremxmS3dTOXQvZHZwQWo0dUpK
        bGtVTDA0bEs2REpyWnZlZGZ0THFDRDAKLS0tIGtjcmdPUWlVM3VOL3VnWE9xdEhk
        WllUem5IZjE0TnZVcVY4MHRRRWFJeG8KrAVrZdaH+hO5ha31vXa1kUZyBtXeht/v
        rOY2/OwVmuMIsG9rVNt1OnV/1fv6FPS3ImCoRIaJAPKGKhGbLZQvYQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-08-18T23:05:48Z"
  mac: ENC[AES256_GCM,data:/cHXJIi65/4y5lgh7khAb7u8X7tfsSyyONfyTZ5TDcyR8wvLPJLUzC/7WI9I0ol34avSDkKdyjlw3uLTS6KSEqt3Ew7yIc5OY8E1o6CbY+gyMdHYGy+fcHdtqCFK0JAo6nc81zy674y7axTk+HjLCB8uCyHobmsx0AxqkGcy6bA=,iv:xeVwD/BQ28eXvovFUMIYiWd3hhajGpa46HvVcDeT5hY=,tag:np6a1w3UQqy/iwjQU8LPdw==,type:str]
  pgp:
    - created_at: "2025-08-16T11:59:51Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hF4DK+ZqT54JVUESAQdAt/hdx7RdHrowsLkpiS3+Owo98xRh7QQAt08XkOoqZAEw
        zS0FEWY4RqLsvKxbBbwAIzJIwM5kA9sleDUCTStxBQ3xLEmw1LM7T5A/af69p0za
        0l4BGLITSrL85+MSIFQyVB8+EQiluycpW4RK1XVea4ph0MgUcNsHNEPaWcZIPXoC
        GUnfWZs/hiOCs+2yvZ6DW3xAmI6l5VNFlUlu2WTN9MlkQ5haZMb+6CubZ3w2ytfS
        =7tAf
        -----END PGP MESSAGE-----
      fp: E23E274D412D4C761A871B1E776C7FC245E58F55
  unencrypted_suffix: _unencrypted
  version: 3.10.2
