let
  # Get system's ssh public key by command:
  #    cat /etc/ssh/ssh_host_ed25519_key.pub
  # If you do not have this file, you can generate all the host keys by command:
  #    sudo ssh-keygen -A
  ymir = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAY49yZ+wLifBGnzCaD/3oN+zs8dH56RX+pNBb/ofdKT root@nixos";
  sigurd = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIP/hbGdtCUOHeLwU2JsV37AK/7lqitLH5zX3XQt5WC+t root@sigurd";

  # A key for recovery purpose, generated by `ssh-keygen -t ed25519 -a 256 -C "johnson@agenix-recovery"` with a strong passphrase
  # and keeped it in a safe place.
  recovery_key = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMNJK6LCNnZM/VXlJIvpDENIs9cIyPfjXZMhg1/ICqW/ johnson@agenix-recovery";
  systems = [
    ymir
    sigurd
    recovery_key
  ];
in {
  "git-credentials.age".publicKeys = systems;
  # "johnson-hu-gpg-primary-key.priv.age.age".publicKeys = systems;
  "johnson-hu-gpg-subkeys.priv.age.age".publicKeys = systems;
  "johnson-hu-ssh-key.age".publicKeys = systems;
}
